### ISSUE TITLE
Diffusion Disconnection Analysis

### ISSUE THREAD

**Issue by sverze2** [rubris/rubris-docs#2]
Hey Steve, I couldn't find an email address to contact you on and I knew you would be paying attention to these issues, so excuse me for raising an issue.

Do you recall when you came in to analyse the Diffusion disconnects and documented your findings?
Basically I am looking for your documentation, do you recall where I could find this?

Steven

**Comment by stevedw** [comment]
Hi Steve,
Its best to ask Ashley. Its on his wiki somwhere.

**Comment by stevedw** [comment]
the outcome was generally a lot was driven by some issue with the client, causing it to ignore the login responses under certain rconnect scenarios.
